"""Tool functions for single_brain.py (Path B — single-LLM architecture).

The Gemini Flash model exposed in `backend/single_brain.py` calls these
three tools to (a) persist captured profile fields, (b) retrieve policy
chunks from Chroma, and (c) mark which policies it has recommended on
the current turn so follow-ups like "tell me more about #2" can resolve.

Each function:
  * Takes plain JSON-serialisable inputs (str / int / list[str]).
  * Returns a plain JSON-serialisable dict that gets fed back to the LLM
    on the next iteration of the function-calling loop.
  * Never raises — failures are surfaced via {"ok": False, "error": "..."}
    so the LLM can decide whether to retry or recover.

The Gemini function-calling DSL (JSON Schema-flavoured) for these three
tools is generated by `single_brain.TOOL_SCHEMAS` from this module's
metadata.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

_log = logging.getLogger(__name__)


# ---- accepted fields for save_profile_field --------------------------------

# Mirrors the slot list in sales_brain._REQUIRED_FOR_READY plus the
# nice-to-have fields the LLM may capture opportunistically. `gender`
# is listed in the spec but is NOT a Profile dataclass field today —
# we silently no-op on it rather than rejecting (forward-compat).
_ACCEPTED_FIELDS = {
    "name",
    "age",
    "dependents",
    "location_tier",
    "income_band",
    "primary_goal",
    "health_conditions",
    "existing_cover_inr",
    "budget_band",
    "gender",  # tolerated; not persisted unless Profile gains the field
}

# These are the slots the brain MUST capture before recommending — same
# list as sales_brain._REQUIRED_FOR_READY. Kept inline (not imported)
# to avoid coupling single_brain to sales_brain.
_REQUIRED_FOR_READY = (
    "name",
    "age",
    "dependents",
    "location_tier",
    "income_band",
    "primary_goal",
    "health_conditions",
)


def _profile_complete(profile) -> bool:
    """Return True when every slot in _REQUIRED_FOR_READY is non-empty on
    the live Profile dataclass."""
    for slot in _REQUIRED_FOR_READY:
        val = getattr(profile, slot, None)
        if val in (None, "", []):
            return False
    return True


# ---- save_profile_field ----------------------------------------------------

def save_profile_field(session, field: str, value: Any) -> dict:
    """Validate + persist a captured profile field on session.profile.

    Accepted fields: name, age, dependents, location_tier, income_band,
                     primary_goal, health_conditions, existing_cover_inr,
                     budget_band, gender (tolerated, may no-op).

    Lightweight normalization:
      - age: int, clamp to [0, 110]
      - dependents: pass through `_normalize_dependents` when available,
        else stringify.
      - existing_cover_inr: parse via `_parse_inr_amount` when available,
        else int-coerce.
      - health_conditions: coerce to list[str], lowercase, strip empties.
      - everything else: string pass-through (Gemini already emits
        canonical values when prompted correctly).

    Returns: {"saved": True, "field": ..., "value": ...,
              "profile_complete": bool}
    On unknown field: {"saved": False, "error": "unknown_field"}
    """
    if not isinstance(field, str) or not field:
        return {"saved": False, "error": "missing_field_name"}

    fld = field.strip().lower()
    if fld not in _ACCEPTED_FIELDS:
        return {"saved": False, "error": f"unknown_field:{field}"}

    profile = session.profile
    normalized: Any = value

    try:
        if fld == "age":
            normalized = _coerce_age(value)
        elif fld == "dependents":
            normalized = _coerce_dependents(value)
        elif fld == "health_conditions":
            normalized = _coerce_health_conditions(value)
        elif fld == "existing_cover_inr":
            normalized = _coerce_existing_cover(value)
        elif fld == "name":
            normalized = (str(value).strip() if value is not None else None) or None
        elif fld == "gender":
            # Profile dataclass has no gender field today; silently
            # accept + skip persistence so the LLM doesn't loop trying
            # to save it. Forward-compat: when Profile gains gender,
            # this branch just becomes `normalized = str(value).strip()`.
            return {
                "saved": False,
                "field": fld,
                "value": value,
                "error": "field_not_on_profile_dataclass",
                "profile_complete": _profile_complete(profile),
            }
        else:
            # location_tier / income_band / primary_goal / budget_band — pass through
            normalized = (str(value).strip() if value is not None else None) or None
    except (TypeError, ValueError) as e:
        return {
            "saved": False,
            "field": fld,
            "value": value,
            "error": f"normalize_failed:{type(e).__name__}:{e}",
        }

    # Drop None/empty so we don't overwrite a previously-captured slot
    # with a Gemini turn that "didn't extract anything". Universal rule
    # from KI-091/094 (extractor null overwrite).
    if normalized in (None, "", []):
        return {
            "saved": False,
            "field": fld,
            "value": value,
            "error": "normalized_empty",
            "profile_complete": _profile_complete(profile),
        }

    if not hasattr(profile, fld):
        return {
            "saved": False,
            "field": fld,
            "value": value,
            "error": "field_not_on_profile_dataclass",
            "profile_complete": _profile_complete(profile),
        }

    setattr(profile, fld, normalized)
    # Track that the brain has "asked" this field so the rest of the
    # codebase's helpers (which inspect profile.asked) stay in sync.
    try:
        if fld not in getattr(profile, "asked", []):
            profile.asked.append(fld)
    except Exception:  # noqa: BLE001 — best-effort bookkeeping
        pass

    return {
        "saved": True,
        "field": fld,
        "value": normalized,
        "profile_complete": _profile_complete(profile),
    }


# ---- retrieve_policies -----------------------------------------------------

async def retrieve_policies(
    query: str,
    top_k: int = 8,
    policy_filter_ids: Optional[list[str]] = None,
    profile=None,
    intent: str = "recommendation",
) -> dict:
    """Call the existing Chroma retriever and return policy chunks.

    Returns:
      {"chunks": [{policy_id, policy_name, insurer_slug, chunk_text,
                   doc_type, source_url, score, ...}, ...],
       "count": N,
       "query": query,
       "guard": optional {reason, fallback} if filter pipeline says abort}

    On failure: {"chunks": [], "count": 0, "error": "..."}.
    """
    if not isinstance(query, str) or not query.strip():
        return {"chunks": [], "count": 0, "error": "empty_query"}

    try:
        from rag.retrieve import retrieve as _retrieve

        chunks = await _retrieve(
            query=query,
            top_k=int(top_k) if top_k else 8,
            policy_ids=policy_filter_ids or None,
        )
    except Exception as e:  # noqa: BLE001 — return graceful empty
        _log.warning(
            "retrieve_policies failed (q=%r): %s: %s",
            query[:120], type(e).__name__, str(e)[:200],
        )
        return {
            "chunks": [],
            "count": 0,
            "error": f"{type(e).__name__}:{str(e)[:200]}",
        }

    raw: list[dict] = []
    for c in chunks or []:
        raw.append(
            {
                "chunk_id": getattr(c, "chunk_id", ""),
                "policy_id": getattr(c, "policy_id", ""),
                "policy_name": getattr(c, "policy_name", ""),
                "insurer_slug": getattr(c, "insurer_slug", ""),
                "doc_type": getattr(c, "doc_type", ""),
                "source_url": getattr(c, "source_url", ""),
                "chunk_text": (getattr(c, "text", "") or "")[:1200],
                "score": float(getattr(c, "score", 0.0) or 0.0),
                "min_entry_age": getattr(c, "min_entry_age", None),
                "max_entry_age": getattr(c, "max_entry_age", None),
            }
        )

    # X5 sidecar: apply profile-fit + citation-grounding + dedup. Skip when
    # caller supplied an explicit policy_filter_ids (we already know which
    # policies they want).
    guard_signal = None
    filtered = raw
    if not policy_filter_ids:
        try:
            from backend.retrieval_filters import filter_pipeline
            filtered, guard_signal = filter_pipeline(
                raw, profile=profile, query=query, intent=intent,
            )
        except Exception as e:  # noqa: BLE001 — pipeline must never break retrieval
            _log.warning("retrieval_filters.filter_pipeline failed: %s", e)
            filtered = raw

    out = {
        "chunks": filtered,
        "count": len(filtered),
        "query": query,
    }
    if guard_signal is not None:
        out["guard"] = guard_signal
    return out


# ---- mark_recommendation ---------------------------------------------------

def mark_recommendation(
    session,
    policy_ids: list[str],
    is_final: bool = False,
) -> dict:
    """Persist the policies just recommended so follow-up turns can resolve
    references like "tell me about #2".

    Sets `session.last_recommendation_ids = policy_ids` (the same field the
    orchestrator already maintains for follow-up routing — KI-224 / KI-228).
    `is_final` is accepted for forward-compat (when the session grows a
    `closed` field); today it's logged but not persisted.

    Returns: {"recorded": True, "policy_ids": [...], "is_final": bool}
    """
    if not isinstance(policy_ids, list):
        return {"recorded": False, "error": "policy_ids_not_list"}

    # Coerce + dedupe while preserving order.
    seen: set[str] = set()
    cleaned: list[str] = []
    for pid in policy_ids:
        s = str(pid).strip()
        if s and s not in seen:
            seen.add(s)
            cleaned.append(s)

    try:
        session.last_recommendation_ids = cleaned
    except Exception as e:  # noqa: BLE001
        return {
            "recorded": False,
            "error": f"setattr_failed:{type(e).__name__}:{e}",
        }

    if is_final and hasattr(session, "closed"):
        try:
            session.closed = True  # type: ignore[attr-defined]
        except Exception:  # noqa: BLE001
            pass

    return {
        "recorded": True,
        "policy_ids": cleaned,
        "is_final": bool(is_final),
    }


# ---- private normalizers ---------------------------------------------------

def _coerce_age(value: Any) -> Optional[int]:
    """int(value), clamped to [0, 110]. Empty / non-numeric → None."""
    if value is None:
        return None
    try:
        if isinstance(value, bool):  # bool is an int subclass — block first
            return None
        n = int(value)
    except (TypeError, ValueError):
        # Try string parse — Gemini sometimes emits "29" as a JSON string
        try:
            n = int(str(value).strip())
        except (TypeError, ValueError):
            return None
    if n < 0:
        n = 0
    if n > 110:
        n = 110
    return n


def _coerce_dependents(value: Any) -> Optional[str]:
    """Delegate to sales_brain_normalizer when importable; else stringify."""
    if value is None:
        return None
    try:
        from backend.sales_brain_normalizer import _normalize_dependents

        # The normalizer signature is (value, schema); pass an empty dict
        # so it falls back to its built-in canonical-string mapping.
        return _normalize_dependents(value, {})
    except Exception:  # noqa: BLE001 — best-effort
        s = str(value).strip()
        return s or None


def _coerce_existing_cover(value: Any) -> Optional[int]:
    """Parse INR amounts like "5L" / "5 lakh" / 500000 via the canonical
    parser. Numeric pass-throughs are clamped to >= 0.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        n = int(value)
        return max(0, n)
    try:
        from backend.needs_finder import _parse_inr_amount

        parsed = _parse_inr_amount(str(value))
        if parsed is not None:
            return max(0, int(parsed))
    except Exception:  # noqa: BLE001
        pass
    # Last-ditch: strip non-digits
    try:
        digits = "".join(ch for ch in str(value) if ch.isdigit())
        if digits:
            return max(0, int(digits))
    except Exception:  # noqa: BLE001
        pass
    return None


def _coerce_health_conditions(value: Any) -> Optional[list[str]]:
    """Always return list[str] lowercase, stripped, empties dropped."""
    if value is None:
        return None
    if isinstance(value, str):
        # Gemini sometimes emits comma-joined strings instead of a list.
        items = [t.strip() for t in value.split(",")]
    elif isinstance(value, (list, tuple)):
        items = [str(t).strip() for t in value]
    else:
        items = [str(value).strip()]
    cleaned = [t.lower() for t in items if t]
    # "none" / "no" → empty list (user explicitly said no conditions).
    cleaned = [t for t in cleaned if t not in {"none", "no", "n/a", "na", "nil"}]
    return cleaned


__all__ = [
    "save_profile_field",
    "retrieve_policies",
    "mark_recommendation",
]
