"""Tool functions for single_brain.py (Path B — single-LLM architecture).

The Gemini Flash model exposed in `backend/single_brain.py` calls these
three tools to (a) persist captured profile fields, (b) retrieve policy
chunks from Chroma, and (c) mark which policies it has recommended on
the current turn so follow-ups like "tell me more about #2" can resolve.

Each function:
  * Takes plain JSON-serialisable inputs (str / int / list[str]).
  * Returns a plain JSON-serialisable dict that gets fed back to the LLM
    on the next iteration of the function-calling loop.
  * Never raises — failures are surfaced via {"ok": False, "error": "..."}
    so the LLM can decide whether to retry or recover.

The Gemini function-calling DSL (JSON Schema-flavoured) for these three
tools is generated by `single_brain.TOOL_SCHEMAS` from this module's
metadata.

═══════════════════════════════════════════════════════════════════════════
SLOT_UNION — SINGLE SOURCE OF TRUTH FOR CAPTURED FIELDS (B6, 2026-05-15)
═══════════════════════════════════════════════════════════════════════════
SLOT_UNION enumerates every captured field that influences EITHER the
recommendation pipeline (retrieval query + scorecard) OR the pricing
pipeline (premium_calculator.estimate / bulk_estimate). It is the contract
between brain_tools (capture surface), single_brain (LLM tool calls),
premium_calculator (pricing inputs) and scorecard (match scoring).

Slot → consumer matrix:

  RECOMMENDATION SLOTS (in _REQUIRED_FOR_READY — hard gate)
    name                  → profile identity (no pricing influence)
    age                   → retrieval query + scorecard + pricing (age band)
    dependents            → retrieval query + scorecard + pricing (family loading)
    location_tier         → retrieval query + scorecard + pricing (location loading)
    income_band           → retrieval query + scorecard
    primary_goal          → retrieval query + scorecard
    health_conditions     → retrieval query + scorecard + pricing (health loading)

  PRICING-ONLY SLOTS (B5 + B6 additions — SOFT capture, post-recap)
    budget_band           → pricing band match
    desired_sum_insured_inr → pricing SI override (per-policy estimate)
    existing_cover_inr    → pricing (existing-cover discount loading)

  FAMILY-DETAIL SLOTS (used by pricing if dependents includes parents)
    parents_to_insure     → triggers parents_loading branch
    parents_age_max       → pricing (parents age loading 1.0× / 1.4× / 1.8×)
    parents_has_ped       → pricing (PED loading inflation for parents)

  D2 ADDITIONS (2026-05-15 — copay + family medical history)
    copay_pct             → pricing (copay discount 1.0× / 0.95× / 0.88× / 0.80×)
    family_medical_history → pricing (family-history loading) + retrieval boost

  KI-275 (2026-05-15 — smoker / tobacco)
    smoker                → pricing (smoker_loading 1.0× / 1.40×, +30-50%)

Total: 16 slots. `gender` is tolerated by save_profile_field for forward
compat but is NOT on the Profile dataclass today; it does not appear in
SLOT_UNION because no consumer reads it.
"""

from __future__ import annotations

import json as _json
import logging
from pathlib import Path
from typing import Any, Optional

from backend.config import settings

_log = logging.getLogger(__name__)


# ───────────────────────────────────────────────────────────────────────────
# KI-278 (2026-05-16) — policy-fact enrichment for the eligibility/ranking
# filter. The Chroma chunk only carries citation metadata; the structural
# facts the eligibility filter needs (top-up signal, sum-insured options,
# mandatory co-pay) live in 40-data/policy_facts/*.json.
#
# IMPORTANT: this code only READS those JSON files and only reads STABLE
# SCHEMA KEYS (policy_type_indemnity_or_fixed / deductible_amount /
# co_payment_pct / sum_insured_options). The concurrent scorecard-repair
# process rewrites the *values*; the *field names* are the contract and do
# not change. We never write to policy_facts/*.json.
#
# A short in-process cache keeps this off the hot path (the catalog is ~250
# files; we only ever touch the ≤8 retrieved per turn, and memoise stems).
# ───────────────────────────────────────────────────────────────────────────

_FACTS_DIR = settings.DATA_DIR / "policy_facts"
_DOCTYPE_SUFFIXES = ("__wordings", "__brochure", "__cis", "__prospectus")
# KI-RECALL-POOL (2026-05-17) — width of the Chroma candidate pool pulled
# BEFORE eligibility + scorecard-aware ranking. Must be wide enough that a
# genuinely-strong A/B policy that is cosine-rank ~15-30 for a profile
# query still enters contention (so the quality-aware filter_pipeline can
# surface it). The LLM still only ever sees the top-k best-fit survivors.
_RECALL_POOL = 40
_FACT_KEYS = (
    "policy_type_indemnity_or_fixed",
    # KI-279 (2026-05-16) — the raw catalog type key. Some curated files
    # (e.g. star-health__star-hospital-cash__brochure.json) carry the
    # product type ONLY under `policy_type` ("hospital_cash") and have NO
    # `policy_type_indemnity_or_fixed` key. Without surfacing this, the
    # retrieval_filters fixed-benefit gate is blind and a daily-cash plan
    # ranks #1 for a comprehensive-indemnity buyer. Read-only; STABLE key.
    "policy_type",
    "deductible_amount",
    "co_payment_pct",
    "sum_insured_options",
    # KI-280 (2026-05-16) — UNIFIED recommendation-fit gate. The eligibility
    # gate needs these STABLE policy_facts keys (read-only):
    #   uin_code            → canonical dedup identity (1 UIN = 1 product;
    #                          collapses marketing-rename / doctype-sibling
    #                          duplicate CITED cards — audit P2/P4/P7).
    #   max_entry_age       → hard eligibility for the INSURED person. When
    #                          the profile insures parents (~70), a plan
    #                          whose max entry age is 65 cannot accept them
    #                          (audit P7). The chunk already carries
    #                          max_entry_age from Chroma metadata, but the
    #                          curated facts file is the authoritative value
    #                          and overrides a missing/None chunk field.
    #   maternity_coverage  → required-feature gate: an explicit maternity /
    #   newborn_coverage      newborn need must rank confirmed plans above
    #                          unconfirmed ones (audit P3).
    # max_renewal_age is intentionally NOT read — it was removed from the
    # scorecard (lifelong renewal is the IRDAI norm; scorecard.py:606).
    "uin_code",
    "max_entry_age",
    "maternity_coverage",
    "newborn_coverage",
)
_facts_cache: dict[str, dict] = {}


def _unwrap(v: Any) -> Any:
    """policy_facts values are `{value, source_pdf_path, source_quote}`
    wrappers OR bare scalars. Return the underlying value either way."""
    if isinstance(v, dict) and "value" in v:
        return v["value"]
    return v


def _candidate_stems(policy_id: str) -> list[str]:
    """A retrieved chunk's policy_id may be the canonical stem
    (`insurer__product`) OR a doctype-suffixed stem
    (`insurer__product__cis`). Try the exact id first, then the canonical
    form, then every doctype sibling — first existing file wins.
    """
    pid = (policy_id or "").strip()
    if not pid:
        return []
    stems = [pid]
    base = pid
    for suf in _DOCTYPE_SUFFIXES:
        if base.endswith(suf):
            base = base[: -len(suf)]
            break
    if base != pid:
        stems.append(base)
    for suf in _DOCTYPE_SUFFIXES:
        cand = base + suf
        if cand not in stems:
            stems.append(cand)
    return stems


def _load_policy_facts(policy_id: str) -> dict:
    """Return {fact_key: value} for a policy_id, or {} when no facts file
    exists / is unreadable. Cached per policy_id (incl. negative cache)."""
    if policy_id in _facts_cache:
        return _facts_cache[policy_id]
    out: dict = {}
    try:
        for stem in _candidate_stems(policy_id):
            fp = _FACTS_DIR / f"{stem}.json"
            if not fp.exists():
                continue
            try:
                d = _json.loads(fp.read_text())
            except Exception:  # noqa: BLE001 — corrupt mid-repair → skip
                continue
            for k in _FACT_KEYS:
                if k in d and k not in out:
                    out[k] = _unwrap(d[k])
            # Stop once we have the decision-critical signals. KI-279: a
            # type signal is "have it" if EITHER the canonical key OR the
            # raw `policy_type` key is present (some files only carry the
            # latter), so the fixed-benefit gate is never starved.
            # KI-280: also require the unified-gate signals (uin_code +
            # max_entry_age) before breaking so the eligibility/dedup rules
            # are not starved when a sibling doctype file carries them. The
            # candidate-stem list is short (≤5) so iterating it fully is
            # cheap; this just stops us breaking after stem #1 when the UIN
            # / entry-age lives in stem #2.
            _have_type = (
                "policy_type_indemnity_or_fixed" in out
                or "policy_type" in out
            )
            if (
                _have_type
                and "sum_insured_options" in out
                and "uin_code" in out
                and "max_entry_age" in out
            ):
                break
    except Exception as e:  # noqa: BLE001 — enrichment must never break retrieval
        _log.warning("KI-278 _load_policy_facts(%s) failed: %s", policy_id, e)
        out = {}
    _facts_cache[policy_id] = out
    return out


_curated_all_cache: dict = {}  # single-slot cache for the full curated layer
_reviews_cache: dict = {}


def _curated_facts_all() -> dict:
    """The FULL curated-facts layer, EXACTLY as the marketplace uses it.

    KI-FULLFACTS (2026-05-17) — root cause of empty recommendation cards:
    `_scorecard_signal` used to feed build_scorecard the 7-key eligibility
    subset (`_load_policy_facts`), which is BELOW build_scorecard's
    data-completeness floor → every recommended policy returned grade "—"
    / overall 0 → the Bug #71 ≥70 gate dropped 100% of them → no cards.
    Meanwhile /api/policies/all scored the SAME policies correctly
    (HDFC Ergo Optima Restore = A/78) because it feeds the FULL curated
    dict from main._load_curated_facts (KI-219/251 canonical precedence).
    We now reuse that EXACT function (lazy import — main is loaded at
    request time; dodges the import cycle) so a policy's recommendation
    grade is identical to its marketplace grade by construction. The
    7-key `_load_policy_facts` stays as-is — it is the correct input for
    the eligibility/dedup gate, NOT for grading."""
    if "d" not in _curated_all_cache:
        from backend.main import _load_curated_facts  # lazy: avoids cycle
        _curated_all_cache["d"] = _load_curated_facts()
    return _curated_all_cache["d"]


def _insurer_reviews(slug: str) -> Optional[dict]:
    """Same reviews source the marketplace passes to build_scorecard
    (40-data/reviews/<slug>.json) — drives the claim-experience sub-score.
    Without it the rec-path grade would drift below the marketplace's."""
    if not slug:
        return None
    if slug in _reviews_cache:
        return _reviews_cache[slug]
    ir = None
    try:
        rp = settings.DATA_DIR / "reviews" / f"{slug}.json"
        if rp.exists():
            ir = _json.loads(rp.read_text())
    except Exception:  # noqa: BLE001 — reviews optional
        ir = None
    _reviews_cache[slug] = ir
    return ir


def _scorecard_signal(policy_id: str, profile=None) -> dict:
    """Best-effort {_grade, _overall_score} from backend.scorecard, using
    the IDENTICAL inputs as the marketplace (/api/policies/all) so a
    policy's recommendation grade == its marketplace grade by construction
    (parity is asserted by tests/test_scorecard_parity.py). READ-ONLY;
    degrades silently to {} on any failure (ranking still works off
    co-pay + SI headroom + cosine)."""
    try:
        cur = _curated_facts_all()
        data = None
        for stem in _candidate_stems(policy_id):
            if stem in cur:
                data = cur[stem]
                break
        if not data:
            # Genuinely unknown policy → fail OPEN (no false weak signal;
            # _recommendation_fit keeps chunks with no grade evidence).
            return {}
        from backend.scorecard import build_scorecard

        slug = data.get("insurer_slug") or (
            policy_id.split("__", 1)[0] if "__" in policy_id else ""
        )
        ir = _insurer_reviews(slug)
        prof = None
        if profile is not None:
            prof = {
                s: getattr(profile, s, None)
                for s in (
                    "age", "income_band", "primary_goal",
                    "existing_cover_inr", "copay_pct",
                )
            }
        sc = build_scorecard(data, insurer_reviews=ir, profile=prof)
        # KI-280 (2026-05-16) — the Scorecard dataclass field is
        # `overall_score` (scorecard.py:95), NOT `overall`. The previous
        # getattr(sc, "overall", ...) ALWAYS returned None, so every
        # enriched chunk reached retrieval_filters with _overall_score=None
        # and _fit_score fell back to the coarse letter-grade table where
        # every "B" == 70.0 exactly. Within-grade order then collapsed to
        # raw cosine — the live audit's grade/rank inversion (P1 C/65 above
        # B/75, P2 A/77 ranked LAST). Read the real numeric field; keep a
        # belt-and-braces `overall` alias for forward-compat.
        _overall = getattr(sc, "overall_score", None)
        if _overall is None:
            _overall = getattr(sc, "overall", None)
        return {
            "_grade": getattr(sc, "grade", None),
            "_overall_score": _overall,
        }
    except Exception:  # noqa: BLE001 — scorecard optional; ranking degrades gracefully
        return {}


# ---- accepted fields for save_profile_field --------------------------------

# Mirrors the slot list in sales_brain._REQUIRED_FOR_READY plus the
# nice-to-have fields the LLM may capture opportunistically. `gender`
# is listed in the spec but is NOT a Profile dataclass field today —
# we silently no-op on it rather than rejecting (forward-compat).
_ACCEPTED_FIELDS = {
    "name",
    "age",
    "dependents",
    "location_tier",
    "income_band",
    "primary_goal",
    "health_conditions",
    "existing_cover_inr",
    "budget_band",
    "desired_sum_insured_inr",  # SOFT capture (pricing input, post-recap)
    # Family-detail pricing inputs (B6) — already on the Profile dataclass
    # via needs_finder.Profile (parents_to_insure / parents_age_max /
    # parents_has_ped). Listed here so save_profile_field can persist them
    # when Gemini extracts them post-recap.
    "parents_to_insure",
    "parents_age_max",
    "parents_has_ped",
    # D2 (2026-05-15) — coupled additions: co-pay tolerance + family medical history
    "copay_pct",
    "family_medical_history",
    # KI-275 (2026-05-15) — smoker / tobacco use, +30-50% premium loading.
    "smoker",
    "gender",  # tolerated; not persisted unless Profile gains the field
}

# These are the slots the brain MUST capture before recommending — same
# list as sales_brain._REQUIRED_FOR_READY. Kept inline (not imported)
# to avoid coupling single_brain to sales_brain.
_REQUIRED_FOR_READY = (
    "name",
    "age",
    "dependents",
    "location_tier",
    "income_band",
    "primary_goal",
    "health_conditions",
)


# ───────────────────────────────────────────────────────────────────────────
# Bug #108 + #110 (2026-05-16) — POST-RECAP pricing & family-history bundle.
#
# Bug #108: the RULE 2.5 bundle (SI / budget / co-pay / family history /
#           smoker) is asked in ONE prompt. When the user answers SOME but
#           not all, the LLM treated the bundle as fully satisfied (it's
#           SOFT capture) and recommended with the unanswered slot blank —
#           e.g. asked SI/budget/co-pay/smoker, user gave SI/budget/co-pay,
#           smoker never re-asked, bot recommended.
# Bug #110: family_medical_history (item 5 of the bundle) was the slot most
#           often silently dropped — the fact-find effectively NEVER asked it.
#
# FIX: a deterministic ONE-SHOT re-ask gate. After the hard 7-slot gate
# passes, on a recommendation retrieve_policies call, if any UNRESOLVED
# bundle slot remains we return a directive `pricing_inputs_incomplete`
# response (re-ask exactly the unresolved ones, verbatim) — but ONLY once
# per session, and ONLY when the user has not explicitly skipped. After the
# single re-ask we proceed (SOFT-capture semantics preserved: the user can
# still skip; we never hard-loop).
#
# A bundle slot is RESOLVED when it is either captured on the profile OR the
# user explicitly declined/skipped it (session.pricing_bundle_skipped — set
# by single_brain when the user says "just show me options" / "skip" / "you
# decide"). parents_age_max is conditional: only part of the bundle when the
# user is covering parents and it isn't captured yet.
_PRICING_BUNDLE_CORE: tuple[str, ...] = (
    "desired_sum_insured_inr",
    "budget_band",
    "existing_cover_inr",
    "copay_pct",
    "family_medical_history",   # Bug #110 — must be asked, same skip handling
    "smoker",
)

# Exact verbatim re-ask phrasing per bundle slot (mirrors RULE 2.5 wording so
# the re-ask reads identically to the first ask). family_medical_history is
# first so a forgotten Bug #110 slot leads the re-ask.
_PRICING_BUNDLE_QUESTIONS: dict[str, str] = {
    "family_medical_history": (
        "Any major conditions running in your blood family "
        "(parents/siblings) — cancer / diabetes / heart disease / "
        "hypertension? (say 'none' if not)"
    ),
    "desired_sum_insured_inr": (
        "How much sum insured would you like? (e.g., ₹5L / ₹10L / "
        "₹25L / ₹1Cr)"
    ),
    "budget_band": (
        "What's your annual premium budget? (e.g., ₹10-15K/year, or "
        "₹50K+ for premium covers)"
    ),
    "existing_cover_inr": (
        "Any existing health cover from work or otherwise? "
        "(e.g., '5L through employer', or 'no')"
    ),
    "copay_pct": (
        "Are you OK with a co-pay — sharing 10-30% of every claim — to "
        "lower the premium? Or do you want zero co-pay?"
    ),
    "smoker": "Do you smoke or use tobacco products? (yes / no)",
    "parents_age_max": (
        "Roughly what's the age of the eldest parent you'd cover?"
    ),
}


def _profile_has_parents(profile) -> bool:
    """True when the captured dependents indicate parents are covered (so
    parents_age_max becomes part of the post-recap bundle)."""
    dep = getattr(profile, "dependents", None)
    if isinstance(dep, str) and "parent" in dep.lower():
        return True
    return bool(getattr(profile, "parents_to_insure", None))


def _unresolved_pricing_bundle(profile, session) -> list[str]:
    """Return the bundle slots that are NEITHER captured on the profile NOR
    explicitly skipped by the user this session. Empty list ⇒ nothing left
    to re-ask (recommend may proceed)."""
    if session is not None and bool(
        getattr(session, "pricing_bundle_skipped", False)
    ):
        # User explicitly said "just show me options / you decide / skip".
        return []
    bundle = list(_PRICING_BUNDLE_CORE)
    if _profile_has_parents(profile):
        bundle.append("parents_age_max")
    unresolved: list[str] = []
    for slot in bundle:
        if getattr(profile, slot, None) in (None, "", []):
            unresolved.append(slot)
    return unresolved


# ───────────────────────────────────────────────────────────────────────────
# SLOT_UNION (B6, 2026-05-15)
# ───────────────────────────────────────────────────────────────────────────
# Single source of truth for every captured field that drives EITHER the
# profile (recommendation match + scorecard) OR the pricing pipeline
# (premium_calculator.estimate / bulk_estimate). See module docstring above
# for the full slot→consumer matrix.
#
# Ordering convention (do not re-order without auditing union_snapshot
# callers): required slots first, then pricing-only slots, then
# family-detail slots. Total = 13.
SLOT_UNION: tuple[str, ...] = (
    # Recommendation slots (in _REQUIRED_FOR_READY)
    "name",
    "age",
    "dependents",
    "location_tier",
    "income_band",
    "primary_goal",
    "health_conditions",
    # Pricing slots (B5 + B6 additions)
    "budget_band",
    "desired_sum_insured_inr",
    "existing_cover_inr",
    # Family-detail slots (used by pricing if applicable)
    "parents_to_insure",
    "parents_age_max",
    "parents_has_ped",
    # D2 additions (2026-05-15)
    "copay_pct",
    "family_medical_history",
    # KI-275 (2026-05-15) — smoker / tobacco use, +30-50% premium loading.
    "smoker",
)

# Invariant: every SLOT_UNION field must be accepted by save_profile_field
# (otherwise the LLM can never capture it). Validated at import time so a
# future delete here is loud, not silent.
assert all(_s in _ACCEPTED_FIELDS for _s in SLOT_UNION), (
    "SLOT_UNION contains a field not in _ACCEPTED_FIELDS: "
    f"{[s for s in SLOT_UNION if s not in _ACCEPTED_FIELDS]}"
)


def union_snapshot(profile) -> dict:
    """Return a JSON-safe dict of every SLOT_UNION field currently captured
    on `profile`. Empty / None / [] slots are EXCLUDED so the pricing
    pipeline can safely treat presence as "captured" (KI-091 null-overwrite
    rule — never pass None where 0 is meaningful).

    Used by premium_calculator.estimate / bulk_estimate to read pricing
    inputs without re-implementing the field-name list on each side.
    """
    snap: dict = {}
    for fld in SLOT_UNION:
        try:
            v = getattr(profile, fld, None)
        except Exception:  # noqa: BLE001
            v = None
        if v in (None, "", []):
            continue
        snap[fld] = v
    return snap


def _profile_complete(profile) -> bool:
    """Return True when every slot in _REQUIRED_FOR_READY is non-empty on
    the live Profile dataclass."""
    for slot in _REQUIRED_FOR_READY:
        val = getattr(profile, slot, None)
        if val in (None, "", []):
            return False
    return True


# ---- save_profile_field ----------------------------------------------------

def save_profile_field(session, field: str, value: Any) -> dict:
    """Validate + persist a captured profile field on session.profile.

    Accepted fields: name, age, dependents, location_tier, income_band,
                     primary_goal, health_conditions, existing_cover_inr,
                     budget_band, gender (tolerated, may no-op).

    Lightweight normalization:
      - age: int, clamp to [0, 110]
      - dependents: pass through `_normalize_dependents` when available,
        else stringify.
      - existing_cover_inr: parse via `_parse_inr_amount` when available,
        else int-coerce.
      - health_conditions: coerce to list[str], lowercase, strip empties.
      - everything else: string pass-through (Gemini already emits
        canonical values when prompted correctly).

    Returns: {"saved": True, "field": ..., "value": ...,
              "profile_complete": bool}
    On unknown field: {"saved": False, "error": "unknown_field"}
    """
    if not isinstance(field, str) or not field:
        return {"saved": False, "error": "missing_field_name"}

    fld = field.strip().lower()
    if fld not in _ACCEPTED_FIELDS:
        return {"saved": False, "error": f"unknown_field:{field}"}

    profile = session.profile
    normalized: Any = value

    try:
        if fld == "age":
            normalized = _coerce_age(value)
        elif fld == "dependents":
            normalized = _coerce_dependents(value)
        elif fld == "health_conditions":
            normalized = _coerce_health_conditions(value)
        elif fld == "existing_cover_inr":
            normalized = _coerce_existing_cover(value)
        elif fld == "desired_sum_insured_inr":
            normalized = _coerce_desired_sum_insured(value)
        elif fld in ("parents_to_insure", "parents_has_ped"):
            normalized = _coerce_bool(value)
        elif fld == "parents_age_max":
            normalized = _coerce_age(value)
        elif fld == "copay_pct":
            normalized = _coerce_copay_pct(value)
        elif fld == "family_medical_history":
            normalized = _coerce_family_medical_history(value)
        elif fld == "smoker":
            normalized = _coerce_smoker(value)
        elif fld == "budget_band":
            normalized = _coerce_budget_band(value)
        elif fld == "name":
            normalized = (str(value).strip() if value is not None else None) or None
        elif fld == "gender":
            # Profile dataclass has no gender field today; silently
            # accept + skip persistence so the LLM doesn't loop trying
            # to save it. Forward-compat: when Profile gains gender,
            # this branch just becomes `normalized = str(value).strip()`.
            return {
                "saved": False,
                "field": fld,
                "value": value,
                "error": "field_not_on_profile_dataclass",
                "profile_complete": _profile_complete(profile),
            }
        else:
            # location_tier / income_band / primary_goal — pass through
            # (budget_band is normalised above via _coerce_budget_band)
            normalized = (str(value).strip() if value is not None else None) or None
    except (TypeError, ValueError) as e:
        return {
            "saved": False,
            "field": fld,
            "value": value,
            "error": f"normalize_failed:{type(e).__name__}:{e}",
        }

    # Drop None/empty so we don't overwrite a previously-captured slot
    # with a Gemini turn that "didn't extract anything". Universal rule
    # from KI-091/094 (extractor null overwrite).
    if normalized in (None, "", []):
        return {
            "saved": False,
            "field": fld,
            "value": value,
            "error": "normalized_empty",
            "profile_complete": _profile_complete(profile),
        }

    if not hasattr(profile, fld):
        return {
            "saved": False,
            "field": fld,
            "value": value,
            "error": "field_not_on_profile_dataclass",
            "profile_complete": _profile_complete(profile),
        }

    setattr(profile, fld, normalized)
    # Track that the brain has "asked" this field so the rest of the
    # codebase's helpers (which inspect profile.asked) stay in sync.
    try:
        if fld not in getattr(profile, "asked", []):
            profile.asked.append(fld)
    except Exception:  # noqa: BLE001 — best-effort bookkeeping
        pass

    return {
        "saved": True,
        "field": fld,
        "value": normalized,
        "profile_complete": _profile_complete(profile),
    }


_qseed_cache: dict = {}  # (profile_sig) -> [seed chunk dicts]


def _quality_seed_candidates(profile, limit: int = 25) -> list[dict]:
    """KI-QUALITY-SEED (2026-05-17). Cosine retrieval is quality-blind: a
    genuinely-best policy whose document wording isn't cosine-similar to a
    generic profile query never enters the candidate pool, so the
    (audit-verified-correct) profile-tuned scorecard + filter_pipeline never
    get the chance to surface it. This deterministically seeds the pool with
    the catalogue's top policies by the PROFILE-TUNED scorecard overall.
    filter_pipeline still does precise eligibility + profile-fit ranking on
    the union (proven: it eligibility-passes + ranks a present A-policy #1),
    so this ONLY guarantees CANDIDACY — it never bypasses eligibility or
    fabricates a recommendation. Pure logic layer: no re-ingest, no vector
    DB change. Cached per profile-signature (the catalogue + a fixed profile
    yield a fixed ranking)."""
    out: list[dict] = []
    try:
        prof_sig = repr(sorted(
            (s, getattr(profile, s, None))
            for s in (
                "age", "income_band", "primary_goal", "existing_cover_inr",
                "copay_pct", "dependents", "health_conditions",
                "budget_band", "location_tier", "parents_to_insure",
                "parents_age_max",
            )
        )) if profile is not None else "none"
        if prof_sig in _qseed_cache:
            return _qseed_cache[prof_sig][:limit]
        cur = _curated_facts_all()
        scored: list[tuple[float, str, dict, dict]] = []
        seen: set[str] = set()
        for key, data in cur.items():
            if not isinstance(data, dict):
                continue
            pid = (data.get("policy_id") or key or "").strip()
            if not pid or pid in seen:
                continue
            seen.add(pid)
            sig = _scorecard_signal(pid, profile=profile)
            ov = sig.get("_overall_score")
            if ov is None:
                continue
            try:
                ovf = float(ov)
            except (TypeError, ValueError):
                continue
            scored.append((ovf, pid, data, sig))
        scored.sort(key=lambda t: -t[0])
        for ovf, pid, data, sig in scored[: max(limit, 25)]:
            ch = {
                "chunk_id": f"{pid}__qseed",
                "policy_id": pid,
                "policy_name": data.get("policy_name", pid),
                "insurer_slug": data.get("insurer_slug")
                or (pid.split("__", 1)[0] if "__" in pid else ""),
                "doc_type": "policy",
                "source_url": data.get("_primary_source_pdf") or "",
                # No cosine text — filter_pipeline ranks the union by
                # _fit_score (scorecard grade + profile fit), not cosine,
                # so a 0.0 cosine score does not bury a seeded A-policy.
                "chunk_text": "",
                "score": 0.0,
            }
            ch.update(_load_policy_facts(pid))
            ch.update(sig)
            out.append(ch)
        _qseed_cache[prof_sig] = out
    except Exception as e:  # noqa: BLE001 — seeding must never break retrieval
        _log.warning("quality-seed failed: %s", e)
    return out[:limit]


# ---- retrieve_policies -----------------------------------------------------

async def retrieve_policies(
    query: str,
    top_k: int = 8,
    policy_filter_ids: Optional[list[str]] = None,
    profile=None,
    intent: str = "recommendation",
    session=None,
    session_id: Optional[str] = None,
) -> dict:
    """Call the existing Chroma retriever and return policy chunks.

    Returns:
      {"chunks": [{policy_id, policy_name, insurer_slug, chunk_text,
                   doc_type, source_url, score, ...}, ...],
       "count": N,
       "query": query,
       "guard": optional {reason, fallback} if filter pipeline says abort}

    On failure: {"chunks": [], "count": 0, "error": "..."}.

    QUARANTINE-RETRIEVAL FIX (2026-05-16) — `session_id` is threaded all the
    way down to `rag.retrieve.retrieve(...)` so a PDF the caller uploaded via
    POST /api/upload-policy (indexed into the SEPARATE
    `user_uploads_quarantine` Chroma collection, tagged with this session's
    id) becomes retrievable BY THE CHAT BRAIN FOR THAT SESSION ONLY. Before
    this fix the upload was embedded but the brain never forwarded
    session_id, so the quarantine boost pass in retrieve.py never fired and
    an uploaded policy could never surface in the conversation. Resolution
    order: explicit `session_id` arg > `session.session_id` attribute >
    None (no quarantine lookup). User A's session_id never leaks into user
    B's retrieval because the quarantine `where={"session_id": ...}` filter
    is strictly equality-scoped (see rag/retrieve.py).
    """
    # Resolve the effective session id. The single_brain dispatcher passes
    # the live SessionState as `session`; older callers may pass session_id
    # explicitly. Never raise — a missing id just means "no quarantine".
    eff_session_id = session_id
    if eff_session_id is None and session is not None:
        eff_session_id = getattr(session, "session_id", None)
    if isinstance(eff_session_id, str):
        eff_session_id = eff_session_id.strip() or None
    elif eff_session_id is not None:
        eff_session_id = None
    if not isinstance(query, str) or not query.strip():
        return {"chunks": [], "count": 0, "error": "empty_query"}

    # Profile-complete gate (skip if caller supplied policy_filter_ids — that
    # branch is a known-policy follow-up). Defense-in-depth: even if the LLM
    # ignores RULE 2 of the system prompt, this refuses to return chunks
    # against an incomplete profile.
    if profile is not None and not policy_filter_ids:
        missing = [
            slot for slot in _REQUIRED_FOR_READY
            if getattr(profile, slot, None) in (None, "", [])
        ]
        if missing:
            # KI-Z6-NONE follow-up (2026-05-15): make the response
            # extremely directive so Gemini doesn't burn an iteration
            # re-trying retrieve_policies on the same incomplete profile.
            # Provide an exact_question string the model can literally
            # relay to the user for the first missing slot.
            _SLOT_QUESTIONS = {
                "name": "What's your name?",
                "age": "How old are you?",
                "dependents": (
                    "Who would you like the cover to include — just you, "
                    "or spouse / kids / parents?"
                ),
                "location_tier": "Which city do you live in?",
                "income_band": (
                    "Roughly what's your annual household income — "
                    "under 10 lakh, 10-25 lakh, or above 25 lakh?"
                ),
                "primary_goal": (
                    "Is this your first health policy, an upgrade, for "
                    "tax planning, or to find a cheaper option?"
                ),
                "health_conditions": (
                    "Do you or your family have any pre-existing health "
                    "conditions like diabetes, BP, or thyroid? If none, "
                    "just say no."
                ),
            }
            first = missing[0]
            return {
                "chunks": [],
                "count": 0,
                "error": "profile_incomplete",
                "missing_slots": missing,
                "action_required": "ask_user_for",
                "field": first,
                "exact_question": _SLOT_QUESTIONS.get(
                    first,
                    f"Could you share your {first.replace('_', ' ')}?",
                ),
                "instruction": (
                    f"Profile is incomplete — missing: {', '.join(missing)}. "
                    "Do NOT call retrieve_policies again this turn. Do NOT "
                    "retry save_profile_field for the same field. Emit a "
                    "TEXT reply that asks the user the `exact_question` "
                    "above verbatim."
                ),
            }

    # Bug #108 + #110 (2026-05-16) — POST-RECAP pricing & family-history
    # bundle re-ask gate. The hard 7-slot gate above is satisfied; before we
    # return chunks for a RECOMMENDATION, ensure every bundle item (SI /
    # budget / existing cover / co-pay / FAMILY MEDICAL HISTORY / smoker /
    # parents-age-if-applicable) has been RESOLVED — captured OR explicitly
    # skipped. If the user answered some but not all, re-ask ONLY the
    # unresolved ones — but exactly ONCE per session (one-shot guard) so we
    # never hard-loop and SOFT-capture semantics survive (the user can still
    # skip on the re-ask). Follow-ups (policy_filter_ids) bypass this — it's
    # purely the first recommendation path.
    if (
        profile is not None
        and not policy_filter_ids
        and (intent or "").lower() == "recommendation"
        and session is not None
        and not bool(getattr(session, "pricing_bundle_reasked", False))
    ):
        unresolved = _unresolved_pricing_bundle(profile, session)
        if unresolved:
            # One-shot: mark so the NEXT recommendation retrieve proceeds
            # even if the user skips on the re-ask (SOFT capture, not a hard
            # gate — Bug #108 fix must re-ask, not loop forever).
            try:
                session.pricing_bundle_reasked = True
            except Exception:  # noqa: BLE001 — bookkeeping must not break
                pass
            _qs = [
                _PRICING_BUNDLE_QUESTIONS.get(
                    s, f"Could you share your {s.replace('_', ' ')}?"
                )
                for s in unresolved
            ]
            _numbered = "\n".join(
                f"{i}. {q}" for i, q in enumerate(_qs, start=1)
            )
            return {
                "chunks": [],
                "count": 0,
                "error": "pricing_inputs_incomplete",
                "missing_slots": unresolved,
                "action_required": "ask_user_for",
                "field": unresolved[0],
                "exact_question": (
                    "Before I pull your recommendations, just a couple more "
                    "(you can skip any):\n" + _numbered
                ),
                "instruction": (
                    "The user answered some but not all of the pricing / "
                    "family-history questions. Do NOT call retrieve_policies "
                    "again this turn and do NOT recommend yet. Emit a TEXT "
                    "reply that asks ONLY the still-missing items in "
                    "`exact_question` verbatim. If the user then provides "
                    "them, save each via save_profile_field; if they skip, "
                    "proceed to retrieve_policies on the next turn."
                ),
            }

    try:
        from rag.retrieve import retrieve as _retrieve

        # KI-RECALL-POOL (2026-05-17) — DECOUPLE the Chroma recall pool from
        # the caller's top_k. Cosine-only Chroma ranking is quality-blind: a
        # mediocre C/D policy whose wording matches the query out-ranks a
        # genuinely-better A/B policy that IS in the corpus. At top_k=8 the
        # A-grade policies never even enter the candidate set, so the
        # downstream quality-aware filter_pipeline (_fit_score, now fed REAL
        # scorecard grades after KI-FULLFACTS) can't surface them — it can
        # only re-order what was retrieved. Fix: retrieve a WIDE pool, let
        # eligibility + scorecard-aware ranking choose, then return the
        # top-k best-fit survivors (truncation happens after filter_pipeline
        # below). For an explicit known-policy follow-up (policy_filter_ids)
        # the caller already knows the policy — keep the narrow top_k.
        _recall_pool = (
            (int(top_k) if top_k else 8)
            if policy_filter_ids
            else _RECALL_POOL
        )
        chunks = await _retrieve(
            query=query,
            top_k=_recall_pool,
            policy_ids=policy_filter_ids or None,
            session_id=eff_session_id,
        )
    except Exception as e:  # noqa: BLE001 — return graceful empty
        _log.warning(
            "retrieve_policies failed (q=%r): %s: %s",
            query[:120], type(e).__name__, str(e)[:200],
        )
        return {
            "chunks": [],
            "count": 0,
            "error": f"{type(e).__name__}:{str(e)[:200]}",
        }

    raw: list[dict] = []
    for c in chunks or []:
        pid = getattr(c, "policy_id", "")
        doc_type = getattr(c, "doc_type", "")
        chunk_dict = {
            "chunk_id": getattr(c, "chunk_id", ""),
            "policy_id": pid,
            "policy_name": getattr(c, "policy_name", ""),
            "insurer_slug": getattr(c, "insurer_slug", ""),
            "doc_type": doc_type,
            "source_url": getattr(c, "source_url", ""),
            "chunk_text": (getattr(c, "text", "") or "")[:1200],
            "score": float(getattr(c, "score", 0.0) or 0.0),
            "min_entry_age": getattr(c, "min_entry_age", None),
            "max_entry_age": getattr(c, "max_entry_age", None),
        }
        # KI-278 — enrich policy chunks with the structural facts the
        # eligibility/profile-fit filter needs (top-up signal, SI options,
        # mandatory co-pay, scorecard grade). Skip non-policy chunks
        # (profile/regulatory/review) — they're never recommendable policies
        # and the eligibility rules don't apply to them.
        if pid and (doc_type or "").lower() not in (
            "profile", "regulatory", "review"
        ):
            try:
                chunk_dict.update(_load_policy_facts(pid))
                chunk_dict.update(_scorecard_signal(pid, profile=profile))
            except Exception as e:  # noqa: BLE001 — never break retrieval
                _log.warning("KI-278 enrich(%s) failed: %s", pid, e)
        raw.append(chunk_dict)

    # X5 sidecar: apply profile-fit + citation-grounding + dedup. Skip when
    # caller supplied an explicit policy_filter_ids (we already know which
    # policies they want).
    guard_signal = None
    filtered = raw
    if not policy_filter_ids:
        # KI-QUALITY-SEED — union the cosine pool with the catalogue's
        # top profile-graded policies so a genuinely-best policy that
        # isn't cosine-similar to a generic needs-query still enters
        # contention. filter_pipeline then does precise eligibility +
        # profile-fit ranking on the union (it eligibility-passes + ranks
        # a present A-policy #1, proven). Cosine chunk wins on dup (it
        # carries real retrieved text); seeds only ADD missing candidates.
        if profile is not None:
            _seen_pids = {
                (c.get("policy_id") or "").strip() for c in raw
            }
            for _seed in _quality_seed_candidates(profile, limit=25):
                _sp = (_seed.get("policy_id") or "").strip()
                if _sp and _sp not in _seen_pids:
                    _seen_pids.add(_sp)
                    raw.append(_seed)
        try:
            from backend.retrieval_filters import filter_pipeline
            filtered, guard_signal = filter_pipeline(
                raw, profile=profile, query=query, intent=intent,
            )
        except Exception as e:  # noqa: BLE001 — pipeline must never break retrieval
            _log.warning("retrieval_filters.filter_pipeline failed: %s", e)
            filtered = raw

        # KI-RECALL-POOL — filter_pipeline has now eligibility-filtered +
        # ranked the WIDE pool best-fit-first (scorecard-aware, deduped to
        # ~1 chunk/policy). Return only the top-N best-fit survivors: enough
        # for the LLM to pick 2-4 strong recommendations AND for the
        # citation builder to select from, without dumping the 40-wide tail
        # as context. This is the ONLY truncation — done AFTER quality
        # ranking, so the genuinely-best eligible policies (e.g. SBI Super
        # Health A/87) are what the LLM and the cards both see. Set on the
        # session cache too so prose ⇄ cited cards are gated on the SAME set.
        filtered = filtered[: max((int(top_k) if top_k else 8), 12)]

    # X7 — cache slug→insurer lookups on session so a subsequent
    # mark_recommendation call (same turn) can stamp the right insurer on the
    # shown_policies event. Each retrieve_policies call MERGES into the cache
    # rather than overwriting, so an LLM that hits multiple retrieves before
    # marking still resolves every cited slug. Keep last_retrieved_chunks too
    # for parity with future tools that need the full chunk objects.
    if session is not None:
        try:
            slug_to_insurer = dict(getattr(session, "slug_to_insurer", {}) or {})
            for c in filtered:
                slug = (c.get("policy_id") or "").strip()
                insurer = (c.get("insurer_slug") or "").strip()
                if slug and insurer:
                    slug_to_insurer[slug] = insurer
            session.slug_to_insurer = slug_to_insurer
            session.last_retrieved_chunks = list(filtered)
        except Exception:  # noqa: BLE001 — bookkeeping must never fail retrieval
            pass

    out = {
        "chunks": filtered,
        "count": len(filtered),
        "query": query,
    }
    if guard_signal is not None:
        out["guard"] = guard_signal
    return out


# ---- mark_recommendation ---------------------------------------------------

def mark_recommendation(
    session,
    policy_ids: list[str],
    is_final: bool = False,
) -> dict:
    """Persist the policies just recommended so follow-up turns can resolve
    references like "tell me about #2".

    Sets `session.last_recommendation_ids = policy_ids` (the same field the
    orchestrator already maintains for follow-up routing — KI-224 / KI-228).
    `is_final` is accepted for forward-compat (when the session grows a
    `closed` field); today it's logged but not persisted.

    Returns: {"recorded": True, "policy_ids": [...], "is_final": bool}
    """
    if not isinstance(policy_ids, list):
        return {"recorded": False, "error": "policy_ids_not_list"}

    # Coerce + dedupe while preserving order.
    seen: set[str] = set()
    cleaned: list[str] = []
    for pid in policy_ids:
        s = str(pid).strip()
        if s and s not in seen:
            seen.add(s)
            cleaned.append(s)

    # Z2 fix — Issue 2 (hallucinated closure). Vikram T6 saw the LLM emit
    # mark_recommendation with an empty policy_ids list, the tool silently
    # returned {"recorded": True, "policy_ids": []}, and the bot then said
    # "I'm glad we found a good fit" despite ZERO cards shown. Two
    # preconditions, gated BEFORE any session write so we don't poison
    # last_recommendation_ids / shown_policies events with junk:
    #   (a) empty (after dedup)  → no_policies_supplied
    #   (b) non-empty BUT no retrieval history this session → caller
    #       must run retrieve_policies first (Y2 cache check via
    #       session.last_retrieved_chunks)
    if not cleaned:
        return {"recorded": False, "error": "no_policies_supplied"}
    _retrieval_cache = getattr(session, "last_retrieved_chunks", None)
    if not _retrieval_cache:
        return {
            "recorded": False,
            "error": "no_retrieval_history — call retrieve_policies first",
        }

    try:
        session.last_recommendation_ids = cleaned
    except Exception as e:  # noqa: BLE001
        return {
            "recorded": False,
            "error": f"setattr_failed:{type(e).__name__}:{e}",
        }

    if is_final and hasattr(session, "closed"):
        try:
            session.closed = True  # type: ignore[attr-defined]
        except Exception:  # noqa: BLE001
            pass

    # X7 — write a shown_policies event per cited policy so the admin
    # Recommendation History panel needs single_brain turns logged the same
    # way the (now-removed) orchestrator did its `_log_shown_policies`
    # (KI-063): dedupe by slug, resolve insurer via the slug→insurer
    # cache `retrieve_policies` stashed on the session this turn, and stamp
    # `turn_idx=session.turn_idx` so the frontend "Conversation turn" column
    # has a real value instead of "—".
    #
    # No profile name → no JSON file to write to (anonymous session). No
    # insurer resolution for a slug → skip that slug. All errors swallowed
    # so a logging failure never breaks the tool reply back to Gemini.
    try:
        profile = getattr(session, "profile", None)
        profile_name = getattr(profile, "name", None) if profile else None
        if profile_name and cleaned:
            from backend.profile_store import record_policy_event

            slug_to_insurer = dict(getattr(session, "slug_to_insurer", {}) or {})
            seen_slugs: set[str] = set()
            turn_idx = int(getattr(session, "turn_idx", 0) or 0)
            session_id = getattr(session, "session_id", None)
            for slug in cleaned:
                if not slug or slug in seen_slugs:
                    continue
                insurer = slug_to_insurer.get(slug)
                if not insurer:
                    # Couldn't resolve insurer this turn — skip rather than
                    # write a malformed event.
                    continue
                seen_slugs.add(slug)
                try:
                    record_policy_event(
                        persona_id_or_name=profile_name,
                        profile=profile,
                        event_type="shown",
                        policy_slug=slug,
                        insurer=insurer,
                        session_id=session_id,
                        reason="shown_in_recommendation",
                        turn_idx=turn_idx,
                    )
                except Exception as inner:  # noqa: BLE001
                    _log.warning(
                        "X7 mark_recommendation record_policy_event "
                        "failed (slug=%s): %s: %s",
                        slug, type(inner).__name__, str(inner)[:200],
                    )
    except Exception as e:  # noqa: BLE001 — never break the tool reply
        _log.warning(
            "X7 mark_recommendation shown-event logging failed: %s: %s",
            type(e).__name__, str(e)[:200],
        )

    return {
        "recorded": True,
        "policy_ids": cleaned,
        "is_final": bool(is_final),
    }


# ---- private normalizers ---------------------------------------------------

def _coerce_age(value: Any) -> Optional[int]:
    """int(value), clamped to [0, 110]. Empty / non-numeric → None."""
    if value is None:
        return None
    try:
        if isinstance(value, bool):  # bool is an int subclass — block first
            return None
        n = int(value)
    except (TypeError, ValueError):
        # Try string parse — Gemini sometimes emits "29" as a JSON string
        try:
            n = int(str(value).strip())
        except (TypeError, ValueError):
            return None
    if n < 0:
        n = 0
    if n > 110:
        n = 110
    return n


# Ported from sales_brain_normalizer.py (B6 cleanup, 2026-05-15) — the legacy
# normalizer module is being deleted; this is the only consumer left.
_DEPENDENT_VAGUE_TERMS = (
    "family", "everyone", "all of us", "everybody",
    "whole family", "joint family",
)


def _normalize_dependents_inline(value: Any) -> Optional[str]:
    """Port of sales_brain_normalizer._normalize_dependents.

    Schema-free variant — the original required a `schema["values"]` lookup
    for direct enum hits; here we hard-code the canonical bucket set used
    by the bot (kept in sync with the previous fact-find schema).
    """
    if not isinstance(value, str):
        return None
    s = value.strip().lower()
    if not s:
        return None
    # Canonical enum values (formerly schema["values"]).
    _CANONICAL_VALUES = (
        "self",
        "self+spouse",
        "self+spouse+kids",
        "self+spouse+parents",
        "self+spouse+kids+parents",
        "self+kids",
        "self+parents",
    )
    if s in _CANONICAL_VALUES:
        return s

    has_spouse = any(k in s for k in ("spouse", "wife", "husband", "partner"))
    has_kids = ("kid" in s) or ("child" in s) or ("children" in s) or ("son" in s) or ("daughter" in s)
    has_parents = "parent" in s

    # Vague terms with no specific signals → cannot coerce
    if any(v in s for v in _DEPENDENT_VAGUE_TERMS) and not (has_spouse or has_kids or has_parents):
        return None

    if has_spouse and has_kids and has_parents:
        return "self+spouse+kids+parents"
    if has_spouse and has_parents:
        return "self+spouse+parents"
    if has_spouse and has_kids:
        return "self+spouse+kids"
    if has_spouse:
        return "self+spouse"
    if has_kids and has_parents:
        # No canonical bucket — fold parents into the wider bundle
        return "self+spouse+kids+parents"
    if has_kids:
        return "self+kids"
    if has_parents:
        return "self+parents"
    # KI-222 — expand the "self" alias set. Live captures showed users
    # answering "single", "unmarried", "no dependents", "just myself" etc.,
    # which previously fell through to None and got silently dropped — the
    # bot then re-asked the same slot on the next turn.
    _SELF_ALIASES = (
        "self", "me", "just me", "only me", "myself", "only self",
        "single", "unmarried", "alone", "bachelor", "no dependents",
        "just myself", "nobody else", "no one else", "nobody",
        "myself only", "by myself", "solo",
    )
    if s in _SELF_ALIASES:
        return "self"
    # Substring fall-through for the same intents when wrapped in extra prose
    # (e.g. "i'm single right now", "just myself for now").
    if any(alias in s for alias in (
        "single", "unmarried", "no dependents", "just myself",
        "by myself", "nobody else", "no one else", "myself only",
        "bachelor", "solo",
    )):
        return "self"
    return None


def _coerce_dependents(value: Any) -> Optional[str]:
    """Normalize raw dependents text to a canonical bucket; see
    `_normalize_dependents_inline` (ported from sales_brain_normalizer)."""
    if value is None:
        return None
    try:
        return _normalize_dependents_inline(value)
    except Exception:  # noqa: BLE001 — best-effort
        s = str(value).strip()
        return s or None


def _coerce_existing_cover(value: Any) -> Optional[int]:
    """Parse INR amounts like "5L" / "5 lakh" / 500000 via the canonical
    parser. Numeric pass-throughs are clamped to >= 0.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        n = int(value)
        return max(0, n)
    try:
        from backend.needs_finder import _parse_inr_amount

        parsed = _parse_inr_amount(str(value))
        if parsed is not None:
            return max(0, int(parsed))
    except Exception:  # noqa: BLE001
        pass
    # Last-ditch: strip non-digits
    try:
        digits = "".join(ch for ch in str(value) if ch.isdigit())
        if digits:
            return max(0, int(digits))
    except Exception:  # noqa: BLE001
        pass
    return None


# Canonical budget bands — the EXACT string contract the frontend
# ProfileBuilderPanel round-trips via budgetBandToInr / budgetInrToBand
# (frontend/src/app/page.tsx) and that needs_finder._parse_budget_band
# emits. Keeping this set inline makes the contract greppable from the
# capture surface.
_CANONICAL_BUDGET_BANDS: frozenset[str] = frozenset(
    {"under_15k", "15k_30k", "30k_60k", "60k+"}
)


def _coerce_budget_band(value: Any) -> Optional[str]:
    """Normalise a budget capture to the documented `budget_band` contract.

    Bug #109 (2026-05-16). The user states a premium budget in chat
    ("max ₹15,000/yr", "around 30k", "15000"). Gemini calls
    save_profile_field(field="budget_band", value=...) but often passes the
    NUMERIC the user said, not a canonical band. The old code let
    budget_band fall through the generic string pass-through, so
    profile.budget_band was stored as the raw "15000" — which the frontend
    ProfileBuilderPanel's budgetBandToInr() switch can't map, so the panel
    never pre-filled the budget slider even though the bot's summary showed
    it.

    Mapping (matches frontend budgetInrToBand + needs_finder bands):
      • already a canonical band ("15k_30k") → passed through unchanged
      • free-text / numeric ("max ₹15,000/yr", "30k", 22000, "10-15K")
        → delegated to needs_finder._parse_budget_band → canonical band
      • unrecognised → None (KI-091 null-overwrite guard then refuses to
        clobber a previously-captured band)
    """
    if value is None:
        return None
    # Numeric → bucket directly (₹ amount per year).
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        v = int(value)
        if v < 15_000:
            return "under_15k"
        if v < 30_000:
            return "15k_30k"
        if v < 60_000:
            return "30k_60k"
        return "60k+"
    s = str(value).strip()
    if not s:
        return None
    # Already canonical — accept verbatim (case/space tolerant).
    norm = s.lower().replace(" ", "")
    if norm in _CANONICAL_BUDGET_BANDS:
        return norm
    # Strip ANNUAL-budget qualifiers FIRST. needs_finder._parse_inr_amount
    # treats a bare "yr" / "year" as an AGE context and refuses to read any
    # number as currency (the KI-161 age guard) — so the canonical live
    # phrasing "max ₹15,000/yr" / "₹15000 per year" parsed to None and the
    # band was never captured (Bug #109). These suffixes are unambiguous
    # PER-ANNUM budget markers here (the field is explicitly the premium
    # budget), not an age, so we drop them before delegating.
    import re as _re

    cleaned = _re.sub(
        r"\b(?:per\s*(?:year|annum)|p\.?\s*a\.?|/\s*(?:yr|year|annum)|"
        r"a\s*year|annually|yearly|/\s*yr)\b",
        " ",
        s,
        flags=_re.IGNORECASE,
    )
    # Free-text / amount → canonical band via the shared parser. This
    # handles "max ₹15,000", "30k", "around 25000", "15-30k", "1 lakh".
    try:
        from backend.needs_finder import _parse_budget_band

        band = _parse_budget_band(cleaned)
        if band in _CANONICAL_BUDGET_BANDS:
            return band
        # Last-resort: if the qualifier strip left only the amount, try the
        # raw string too (covers phrasings the regex didn't anticipate).
        if cleaned != s:
            band = _parse_budget_band(s)
            if band in _CANONICAL_BUDGET_BANDS:
                return band
    except Exception:  # noqa: BLE001 — parser optional; fall through to None
        pass
    return None


def _coerce_bool(value: Any) -> Optional[bool]:
    """Tri-state bool coercion for parents_to_insure / parents_has_ped.

    Accepts: True / False / "yes" / "no" / "y" / "n" / "true" / "false"
    / 1 / 0. Anything else → None (so the KI-091 null-overwrite guard
    refuses to clobber a previously-captured value).
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    s = str(value).strip().lower()
    if s in ("true", "yes", "y", "1"):
        return True
    if s in ("false", "no", "n", "0"):
        return False
    return None


def _coerce_smoker(value: Any) -> Optional[bool]:
    """KI-275 (2026-05-15) — tri-state bool for smoker / tobacco use.

    Accepts:
      - True / "yes" / "true" / "smoker" / "smokes" / "tobacco" / 1  → True
      - False / "no" / "false" / "non-smoker" / "doesn't smoke" / 0  → False
      - None / "" / unclear                                          → None

    Returning None lets the KI-091 null-overwrite guard in
    save_profile_field refuse to clobber a previously-captured value.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    s = str(value).strip().lower()
    if not s:
        return None
    _YES = {
        "yes", "y", "true", "1",
        "smoker", "smokes", "smoke", "i smoke",
        "tobacco", "tobacco user", "uses tobacco",
        "i do", "yep", "yeah", "yup",
    }
    _NO = {
        "no", "n", "false", "0",
        "non-smoker", "nonsmoker", "non smoker",
        "doesn't smoke", "does not smoke", "dont smoke", "don't smoke",
        "i don't", "i do not", "nope", "never", "no tobacco",
    }
    if s in _YES:
        return True
    if s in _NO:
        return False
    # Substring fall-through for prose ("I'm a non-smoker", "I smoke daily").
    if any(tok in s for tok in ("non-smoker", "nonsmoker", "non smoker", "don't smoke",
                                 "doesn't smoke", "do not smoke", "no tobacco")):
        return False
    if any(tok in s for tok in ("smoker", "smokes", "tobacco")):
        return True
    return None


def _coerce_desired_sum_insured(value: Any) -> Optional[int]:
    """Parse desired sum insured (cover amount) as integer rupees.

    Accepts: "10L" / "10 lakh" / "1 crore" / "1Cr" / 1000000 /
    "₹10,00,000" / "five lakh" (rejected — words not numerals).
    Delegates to `_parse_inr_amount` from needs_finder for the heavy lift,
    falls back to bare-digit extraction. Clamps to [50_000, 500_000_000]
    (₹50K floor, ₹50Cr ceiling) — anything outside is implausible for a
    health-insurance sum insured and likely a parse error.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        n = int(value)
        return max(50_000, min(500_000_000, n))
    try:
        from backend.needs_finder import _parse_inr_amount

        parsed = _parse_inr_amount(str(value))
        if parsed is not None:
            return max(50_000, min(500_000_000, int(parsed)))
    except Exception:  # noqa: BLE001
        pass
    # Last-ditch: strip non-digits (handles "₹10,00,000" if parser missed).
    try:
        digits = "".join(ch for ch in str(value) if ch.isdigit())
        if digits:
            n = int(digits)
            if n >= 50_000:
                return min(500_000_000, n)
    except Exception:  # noqa: BLE001
        pass
    return None


def _coerce_health_conditions(value: Any) -> Optional[list[str]]:
    """Always return list[str] lowercase, stripped, empties dropped.

    KI-Z6-NONE (2026-05-15): "none" / "no" / "n/a" — used to be stripped to
    `[]`, but downstream `save_profile_field` then hits the KI-091 null-
    overwrite guard (`normalized in (None, "", [])`) and refuses to persist
    the slot. Result: profile.health_conditions stays empty forever,
    `_profile_complete` returns False, retrieve_policies returns
    profile_incomplete, the brain loops, MAX_ITERATIONS exhausts, the bot
    emits "Sorry — I lost my train of thought" (W1 Turn 3 live blocker).

    Fix: keep the explicit-negation sentinel `["none"]` so:
      • the slot is non-empty → _profile_complete=True → retrieve fires
      • downstream consumers can still detect "no PED" via the literal
        token `"none"` in the list (callers already lowercase-compare).
    """
    if value is None:
        return None
    if isinstance(value, str):
        # Gemini sometimes emits comma-joined strings instead of a list.
        items = [t.strip() for t in value.split(",")]
    elif isinstance(value, (list, tuple)):
        items = [str(t).strip() for t in value]
    else:
        items = [str(value).strip()]
    cleaned = [t.lower() for t in items if t]
    # Explicit-negation tokens — collapse to the canonical sentinel
    # `["none"]` rather than `[]` so the slot is captured, not blanked.
    _NEGATION = {"none", "no", "n/a", "na", "nil", "nothing", "healthy"}
    if cleaned and all(t in _NEGATION for t in cleaned):
        return ["none"]
    # Mixed input ("diabetes, none") — drop the negation noise, keep real
    # conditions.
    real = [t for t in cleaned if t not in _NEGATION]
    return real


# ---------------------------------------------------------------------------
# D2 (2026-05-15) — copay_pct + family_medical_history coercers
# ---------------------------------------------------------------------------

# Word-number map for "twenty", "ten" etc. (RULE 2.5 asks the user in
# multiples of 10; Gemini sometimes echoes the user's word verbatim).
_COPAY_WORD_TO_INT: dict[str, int] = {
    "zero": 0, "none": 0, "no": 0,
    "ten": 10, "fifteen": 15, "twenty": 20,
    "twenty five": 25, "twenty-five": 25,
    "thirty": 30, "forty": 40, "fifty": 50,
}


def _coerce_copay_pct(value: Any) -> Optional[int]:
    """Parse a co-pay tolerance percent, clamped to [0, 50].

    Accepts:
      - int / float  → int + clamp
      - "20", "20%", "  20 % ", "20 percent" → 20
      - "no copay" / "zero" / "none" → 0
      - word numbers like "twenty" → 20
      - bool → blocked (KI-091 null-overwrite caution: bool is an int subclass)

    Returns None for unrecognised input so the null-overwrite guard in
    save_profile_field can refuse to clobber a previously-captured slot.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        n = int(value)
        return max(0, min(50, n))
    s = str(value).strip().lower()
    if not s:
        return None
    # Explicit zero phrasings.
    if s in ("no", "none", "nil", "zero", "no copay", "no co-pay", "no co pay"):
        return 0
    # Word-number lookup (exact match).
    if s in _COPAY_WORD_TO_INT:
        return _COPAY_WORD_TO_INT[s]
    # Strip "%" + "percent" + "pct".
    cleaned = (
        s.replace("%", " ")
         .replace("percent", " ")
         .replace("pct", " ")
         .replace("copay", " ")
         .replace("co-pay", " ")
         .replace("co pay", " ")
    )
    # Digit run.
    import re as _re
    m = _re.search(r"\d+(?:\.\d+)?", cleaned)
    if m:
        try:
            n = int(float(m.group(0)))
            return max(0, min(50, n))
        except ValueError:
            return None
    # Word-number fall-through (substring on cleaned text).
    for word, num in _COPAY_WORD_TO_INT.items():
        if word in cleaned.split():
            return num
    return None


# Alias map for family medical history — same canonicalisation logic as
# health_conditions but kept inline so this slot stays self-contained.
_FAMILY_HISTORY_ALIASES: dict[str, str] = {
    "bp": "hypertension",
    "high bp": "hypertension",
    "high-bp": "hypertension",
    "hi-bp": "hypertension",
    "high blood pressure": "hypertension",
    "blood pressure": "hypertension",
    "sugar": "diabetes",
    "diabetic": "diabetes",
    "type 2 diabetes": "diabetes",
    "type 1 diabetes": "diabetes",
    "heart attack": "heart",
    "heart disease": "heart",
    "cardiac": "heart",
    "cardiac disease": "heart",
    "stroke": "heart",
    "tumor": "cancer",
    "tumour": "cancer",
    "carcinoma": "cancer",
}

_FAMILY_HISTORY_NEGATION = {
    "none", "no", "n/a", "na", "nil", "nothing", "healthy",
    "no family history", "no history", "no medical history",
}


def _coerce_family_medical_history(value: Any) -> Optional[list[str]]:
    """Return list[str] lowercase canonical conditions running in BLOOD family.

    Accepts:
      - list / tuple of strings
      - comma-joined string ("cancer, diabetes")
      - "none" / "no family history" → []

    Alias map collapses BP/sugar/cardiac/tumor → hypertension/diabetes/heart/
    cancer respectively (same family as _coerce_health_conditions). Negation
    sentinels return `[]` since downstream pricing & retrieval BOTH treat an
    empty list as the "no family history" branch (different from health_
    conditions where the explicit `["none"]` sentinel is needed for the
    profile-completeness gate).
    """
    if value is None:
        return None
    if isinstance(value, str):
        items = [t.strip() for t in value.split(",")]
    elif isinstance(value, (list, tuple)):
        items = [str(t).strip() for t in value]
    else:
        items = [str(value).strip()]
    cleaned = [t.lower() for t in items if t]
    # Full-string negation collapses to [].
    if cleaned and all(t in _FAMILY_HISTORY_NEGATION for t in cleaned):
        return []
    # Drop negation noise from mixed input ("cancer, none").
    cleaned = [t for t in cleaned if t not in _FAMILY_HISTORY_NEGATION]
    # Canonicalise via alias map.
    canonical: list[str] = []
    seen: set[str] = set()
    for t in cleaned:
        c = _FAMILY_HISTORY_ALIASES.get(t, t)
        if c and c not in seen:
            seen.add(c)
            canonical.append(c)
    return canonical


__all__ = [
    "save_profile_field",
    "retrieve_policies",
    "mark_recommendation",
    "SLOT_UNION",
    "union_snapshot",
]
