"""One-shot uploader to Hugging Face Space (post-D-019 — code-only).

Pushes the code-only Space (minus build artifacts, .venv, node_modules, etc.) to
huggingface.co/spaces/rohitsar567/InsuranceBot. Post-D-019 the large data
(corpus PDFs + Chroma vectors + extracted JSONs) lives in the companion HF
dataset rohitsar567/insurance-bot-data — the Space's Dockerfile pulls it via
huggingface_hub.snapshot_download at image build time.

Run:
  python tools/upload_to_hf.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from huggingface_hub import HfApi

ROOT = Path(__file__).resolve().parent.parent
load_dotenv(ROOT / ".env")

REPO_ID = "rohitsar567/InsuranceBot"
REPO_TYPE = "space"

# Everything we DON'T want shipped to the Space. Post-D-019 the data dirs
# (corpus / vectors / extracted) live in the companion dataset and are
# pulled at Docker build time, NOT pushed via the Space repo.
IGNORE = [
    ".git/**",
    ".venv/**",
    "venv/**",
    "**/__pycache__/**",
    "**/*.pyc",
    "node_modules/**",
    "frontend/node_modules/**",
    "frontend/.next/**",
    "frontend/out/**",  # rebuilt inside Docker
    ".env",
    ".env.local",
    "**/.DS_Store",
    "logs/**",
    "*.log",
    # Data — lives in rohitsar567/insurance-bot-data dataset (D-019).
    # Don't ship here; the Dockerfile snapshot_downloads them at build.
    "rag/corpus/**",
    "rag/vectors/**",
    "rag/extracted/**",
    # KI-128 (2026-05-15): backup dir + LFS pointers were leaking into the
    # Space push via the rag/corpus and rag/extracted symlinks, blowing the
    # Space's 1 GB LFS storage quota (Repository storage limit reached on
    # post_lfs_batch_info). The data path is HF Dataset, NOT the Space.
    "rag/_hf_dataset_backup/**",
    "**/_hf_dataset_backup/**",
    "rag/policies.duckdb",      # LFS-tracked, comes from dataset at build
    "rag/source_map.json",      # tiny but rebuilt by source_map.py
    ".playwright-mcp/**",       # Browser snapshots from local Playwright sessions
    "eval/results.json",        # Regenerated by eval runs
    "eval/chunk_*.json",        # Sweep artifacts
    "kb/calculations/chunk_*",  # Sweep markdown
]


def main():
    token = os.environ.get("HF_TOKEN", "")
    if not token:
        print("ERROR: HF_TOKEN not in environment (or .env)")
        return 1

    api = HfApi(token=token)
    print(f"Uploading {ROOT} (code only) -> https://huggingface.co/spaces/{REPO_ID}")
    print("(data is fetched from the companion dataset at Docker build time)")

    api.upload_folder(
        folder_path=str(ROOT),
        repo_id=REPO_ID,
        repo_type=REPO_TYPE,
        ignore_patterns=IGNORE,
        commit_message="Deploy: Stack A (NIM brain + Maverick judge + Sarvam voice). D-019.",
    )

    print()
    print("✓ Upload complete.")
    print(f"  Space:    https://huggingface.co/spaces/{REPO_ID}")
    print(f"  Embed:    https://rohitsar567-insurancebot.hf.space")
    print()
    print("Required Space secrets (set via tools/set_hf_secrets.py):")
    print("  SARVAM_API_KEY       — voice STT/TTS + Indic translation")
    print("  VOYAGE_API_KEY       — legacy embeddings (kept for back-compat)")
    print("  NVIDIA_NIM_API_KEY   — brain (V4-Pro / V4-Flash) + judge (Llama-4 Maverick)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
